twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # Autres configurations existantes si vous en avez

when@test:
    twig:
        strict_variables: true